version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: build
    container_name: task-manager-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host
    environment:
      - NODE_ENV=development